version: '3'

services:

  nats-server:
    image: nats:latest

  #---------------------------------------------------------
  # CLIENT GATEWAY
  #---------------------------------------------------------
  client-gateway:
    image: gateway-prod
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  #---------------------------------------------------------
  # AUTH MICROSERVICE
  #---------------------------------------------------------
  auth-ms:
    image: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}

  #---------------------------------------------------------
  # PRODUCTS MICROSERVICE
  #---------------------------------------------------------
  products-ms:
    image: products-ms
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=3000
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  #---------------------------------------------------------
  # ORDERS MICROSERVICE
  #---------------------------------------------------------

  orders-ms:
    image: orders-ms
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

  #---------------------------------------------------------
  # PAYMENTS MICROSERVICE
  #---------------------------------------------------------
  payments-ms:
    image: payments-ms
    build: ./payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_WEBHOOK_ENDPOINT_SECRET=${STRIPE_WEBHOOK_ENDPOINT_SECRET}
